[package]
name = "smash"
version = "0.0.0-alpha.4"
authors = ["Jian Chen <admin@chensoft.com>"]
edition = "2021"
description = "Placeholder"
documentation = "https://docs.rs/smash"
readme = "README.md"
repository = "https://github.com/chensoft/smash"
license = "MIT"
keywords = []

[[bench]]
name = "playground"
harness = false

[[bench]]
name = "benchmark"
harness = false

[dev-dependencies]
anyhow = "1.0"
criterion = { version = "0.5", features = ["async_tokio"] }

[dependencies]
tokio = { version = "1", features = ["full"] }
thiserror = "2.0"
async-trait = "0.1"